name: "Test all features"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Cancel a currently running workflow from the same PR, branch or tag when a new workflow is
# triggered (ref https://stackoverflow.com/a/72408109)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Install updates and protobuf-compiler
        run: sudo apt update && sudo apt install --assume-yes cmake protobuf-compiler

      - name: Free space on the runner
        run: |
          df -h
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch cache
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2.7.0

      - name: Test
        run: cargo test --workspace --release --locked -q --features=runtime-metrics,try-runtime
        env:
          RUSTFLAGS: "-C debug-assertions -D warnings"
          SKIP_WASM_BUILD: 1

      - name: Test all features
        run: cargo test --workspace --release --locked -q --features=runtime-benchmarks,runtime-metrics,try-runtime
        env:
          RUSTFLAGS: "-C debug-assertions -D warnings"
          SKIP_WASM_BUILD: 1